version: '3'
services:
  bbs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/project/bbs
  nginx:
    image: nginx:alpine
    ports:
      - "83:83"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bbs

